# Use an official Debian as a parent image
FROM debian:buster-slim

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && apt-get install -y \
    x11vnc \
    novnc \
    pulseaudio \
    pulseaudio-module-x11 \
    pulseaudio-module-native \
    pulseaudio-module-zeroconf \
    pulseaudio-module-bluetooth \
    pulseaudio-module-alsa \
    pulseaudio-module-oss \
    pulseaudio-module-pipewire \
    pulseaudio-module-pipewire-alsa \
    pulseaudio-module-pipewire-jack \
    pulseaudio-module-pipewire-pulse \
    pulseaudio-module-pipewire-rt \
    pulseaudio-module-pipewire-sink \
    pulseaudio-module-pipewire-source \
    pulseaudio-module-pipewire-stream \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire-stream-source \
    pulseaudio-module-pipewire-stream-alsa \
    pulseaudio-module-pipewire-stream-jack \
    pulseaudio-module-pipewire-stream-pulse \
    pulseaudio-module-pipewire-stream-rt \
    pulseaudio-module-pipewire-stream-sink \
    pulseaudio-module-pipewire # Ensure all necessary modules are listed here

# Set up PulseAudio
RUN mkdir -p /etc/pulse
RUN echo "default-server = 127.0.0.1" > /etc/pulse/client.conf

# Set up NoVNC
RUN mkdir -p /usr/share/novnc
COPY novnc /usr/share/novnc

# Set up x11vnc
RUN mkdir -p /usr/share/x11vnc
COPY x11vnc /usr/share/x11vnc

# Set up the entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Expose the necessary ports
EXPOSE 6980

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
